# Cheie OpenAI
OPENAI_API_KEY = "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"

# Notificări Telegram
TELEGRAM_TOKEN = "tokenul_tău_aici"
TELEGRAM_CHAT_ID = "8766569482"

# Trimite Mail
GMAIL_USER = "chitu.delia123@gmail.com"
GMAIL_PASSWORD = "eeqlnbxxpzpzwdbj"